// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  model

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CreateOrderReqDelivery ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateOrderReqDelivery ) UnmarshalJSON([]byte) error { return nil }
func ( CreateOrderReqDelivery ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateOrderReqDelivery ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateOrderReqDelivery *CreateOrderReqDelivery

func ( CreateOrderResDelivery ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateOrderResDelivery ) UnmarshalJSON([]byte) error { return nil }
func ( CreateOrderResDelivery ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateOrderResDelivery ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateOrderResDelivery *CreateOrderResDelivery

func ( OrderItem ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* OrderItem ) UnmarshalJSON([]byte) error { return nil }
func ( OrderItem ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* OrderItem ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OrderItem *OrderItem
