// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package rest

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest(in *jlexer.Lexer, out *ListCoffeeRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "coffee_list":
			if in.IsNull() {
				in.Skip()
				out.CoffeeList = nil
			} else {
				in.Delim('[')
				if out.CoffeeList == nil {
					if !in.IsDelim(']') {
						out.CoffeeList = make([]Coffee, 0, 0)
					} else {
						out.CoffeeList = []Coffee{}
					}
				} else {
					out.CoffeeList = (out.CoffeeList)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Coffee
					(v1).UnmarshalEasyJSON(in)
					out.CoffeeList = append(out.CoffeeList, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest(out *jwriter.Writer, in ListCoffeeRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coffee_list\":"
		out.RawString(prefix[1:])
		if in.CoffeeList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.CoffeeList {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListCoffeeRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListCoffeeRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListCoffeeRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListCoffeeRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest(l, v)
}
func easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest1(in *jlexer.Lexer, out *ListCoffeeReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "offset":
			out.Offset = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest1(out *jwriter.Writer, in ListCoffeeReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListCoffeeReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListCoffeeReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListCoffeeReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListCoffeeReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest1(l, v)
}
func easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest2(in *jlexer.Lexer, out *GetCoffeeRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "coffee":
			(out.Coffee).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest2(out *jwriter.Writer, in GetCoffeeRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coffee\":"
		out.RawString(prefix[1:])
		(in.Coffee).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetCoffeeRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCoffeeRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCoffeeRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCoffeeRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest2(l, v)
}
func easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest3(in *jlexer.Lexer, out *GetCoffeeReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.CoffeeID = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest3(out *jwriter.Writer, in GetCoffeeReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.CoffeeID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetCoffeeReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCoffeeReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCoffeeReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCoffeeReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest3(l, v)
}
func easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest4(in *jlexer.Lexer, out *Coffee) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint64(in.Uint64())
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "image":
			out.Image = string(in.String())
		case "weight":
			out.Weight = uint64(in.Uint64())
		case "price":
			out.Price = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest4(out *jwriter.Writer, in Coffee) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"image\":"
		out.RawString(prefix)
		out.String(string(in.Image))
	}
	{
		const prefix string = ",\"weight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Weight))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Float64(float64(in.Price))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Coffee) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Coffee) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDfb66c62EncodeCoffeeshopApiInternalServiceCoffeeDeliveryRest4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Coffee) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Coffee) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDfb66c62DecodeCoffeeshopApiInternalServiceCoffeeDeliveryRest4(l, v)
}
